### ISSUE TITLE
Docker-Image stopped working

### ISSUE THREAD

**Issue by boenni23** [freekode/tp2intervals#96]
Thanks for the app.

I have a docker setup running for some time now.

```
services:
  app:
    restart: unless-stopped
    image: ghcr.io/freekode/tp2intervals/tp2intervals:latest
    container_name: tp2intervals
    ports:
      - '8081:8080'
    volumes:
      - /root/data/training/tp2intervals.sqlite:/tp2intervals.sqlite
``` 

But the GUI gives this error.
```
Http failure response for http://localhost:8080/api/configuration: 0 Unknown Error
```

Somehow it tries to connect to `localhost`. I my case it is on a different Server. Can this be configured somewhere?
I tried this but it did not work either
` -Dspring-boot.run.arguments="--server.address=0.0.0.0 --server.port=8081"`
